server:
  port: 8080
  undertow:
     io-threads:16
     worker-threads:256
     buffer-size:1024
     buffers-per-region:1024
     direct-buffers:true
logging: 
  file: /data/logs/test/springboot1-test/application.log

      
#    platform: postgres
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/ntabase?useSSL=false
#    username: postgres
#    password: 123456
#  jpa:
#    database: postgresql
#    show-sql: true
#    hibernate: 
#      ddl-auto: update
#    properties:
#        hibernate:
#          dialect: org.hibernate.dialect.PostgreSQL94Dialect
   