server:
  port: 8080
logging: 
  file: /data/logs/springboot1-learn/application.log

      
#    platform: postgres
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/ntabase?useSSL=false
#    username: postgres
#    password: 123456
#  jpa:
#    database: postgresql
#    show-sql: true
#    hibernate: 
#      ddl-auto: update
#    properties:
#        hibernate:
#          dialect: org.hibernate.dialect.PostgreSQL94Dialect
   